name: Terraform Build

on:
  push:
    branches:
      - master
    paths:
      - infrastructure/terraform/setup/**
      - .github/workflows/terraform_setup_dev.yml

env:
  AWS_DEFAULT_REGION: ap-northeast-1
  TF_WORKSPACE: dev
  TF_VAR_region: ap-northeast-1

jobs:
  Update:
    runs-on: ubuntu-18.04
    environment:
      name: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # source checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI 
      # and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Setup init
      - name: Terraform Init
        working-directory: infrastructure/terraform/setup
        run: terraform init

      # Setup plan
      - name: Terraform Plan
        working-directory: infrastructure/terraform/setup
        run: terraform plan -out=setup
        env:
          TF_VAR_translation_api_key: ${{ secrets.TRANSLATION_API_KEY }}
          TF_VAR_ipa_api_key: ${{ secrets.IPA_API_KEY }}
          TF_VAR_dns_name_servers:  ${{ secrets.DNS_NAME_SERVERS }}
          TF_VAR_identity_provider_id:  ${{ secrets.IDENTITY_PROVIDER_ID }}
          TF_VAR_identity_provider_secret:  ${{ secrets.IDENTITY_PROVIDER_SECRET }}

      # Setup apply
      - name: Terraform Apply
        working-directory: infrastructure/terraform/setup
        run: terraform apply "setup"
